services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    labels:
      - "traefik.enable=true"
    networks:
      - traefik_default
    volume:
      - ./.env/.minio.front:/app/.env/.minio

  backend:
    build:
      context: ./backend
    volume:
      - ./.env/.minio:/app/.env/.minio
      - ./local:/app/local
      - ./models/base/text_tower.py:/app/model.py
    container_name: backend

networks:
  traefik_default:
    external: true
